### ISSUE TITLE
Button or Tatoo?

### ISSUE THREAD

**Issue by anicake** [malinoff/tatoo#3]
I'm just deciding to come over from PyInvoke due to my inability to grasp the concepts about state sharing using Contexts in there... Now here I come and the main page says `button` but `fork me on github` leads to `tatoo` and PyPi has not package called `button` but has one called `tatoo`.

I'm confused.

**Comment by malinoff** [comment]
@anicake hi, sorry for this confusion. I should definitely clean up these links, but as you can see from the history, I do not actively maintain this project (mainly due to my daily job), and I don't expect to have any time for it in the nearest future.

I'd suggest to explore http://pydoit.org/ and http://paver.github.io/paver/ instead. Thanks for your attention anyway!
